
const Avatar = (avatar) => {
	switch(avatar) {
		case 'nabil1':
			return require('./images/nabil.jpg');
		case 'asif2':
			return require('./images/asif.jpg');
		case 'amanat3':
			return require('./images/amanat.jpg');
		case 'tuli4':
			return require('./images/tuli.jpg');
		case 'prionty5':
			return require('./images/prionty.jpg');
		case 'mahabubul7':
			return require('./images/mahabubul.jpg');
		case 'zulkarnain8':
			return require('./images/sajid.jpg');
		case 'abbas9':
			return require('./images/abbas.jpg');
		case 'orin10':
			return require('./images/orin.jpg');
		case 'halima11':
			return require('./images/halima.jpg');
		case 'susmita12':
			return require('./images/susmita.jpg');
		case 'bithy13':
			return require('./images/bithy.jpg');
		case 'sakib14':
			return require('./images/shakib.jpg');
		case 'monirul15':
			return require('./images/monirul.jpg');
		case 'uttom16':
			return require('./images/uttom.jpg');
		case 'nazmul17':
			return require('./images/nazmul.jpg');
		case 'shourav19':
			return require('./images/sourav.jpg');
		case 'momenul20':
			return require('./images/momenul.jpg');
		case 'ataur21':
			return require('./images/ataur.jpg');
		case 'shawon23':
			return require('./images/shawon.jpg');
		case 'tamanna24':
			return require('./images/tamanna.jpg');
		case 'jahirul26':
			return require('./images/jaharul.jpg');
		case 'limon27':
			return require('./images/limon.jpg');
		case 'fahin29':
			return require('./images/fahim.jpg');
		case 'porimal30':
			return require('./images/porimal.jpg');
		case 'noyon31':
			return require('./images/noyon.jpg');
		case 'sonot32':
			return require('./images/sonot.jpg');
		case 'salahuddin34':
			return require('./images/salauddin.jpg');
		case 'rasel35':
			return require('./images/rasel.jpg');
		case 'mafuza36':
			return require('./images/mahfuza.jpg');
		case 'nipa37':
			return require('./images/nipa.jpg');
		case 'anika38':
			return require('./images/anika.jpg');
		case 'yeasin39':
			return require('./images/yeasin.jpg');
		case 'mahafuzur41':
			return require('./images/mahfuz.jpg');
		case 'pias42':
			return require('./images/kousik.jpg');
		case 'abida43':
			return require('./images/abida.jpg');
		case 'sadik44':
			return require('./images/sadik.jpg');
		case 'nazmul45':
			return require('./images/nazmulhq.jpg');
		case 'arnob46':
			return require('./images/arnob.jpg');
		case 'jiarul47':
			return require('./images/jiarul.jpg');
		case 'ferdous48':
			return require('./images/ferdous.jpg');
		case 'rakib49':
			return require('./images/profile.jpg');
		case 'monir50':
			return require('./images/monir.jpg');
		case 'barik51':
			return require('./images/barik.jpg');
		case 'mozahid52':
			return require('./images/muzahid.jpg');
		case 'imran54':
			return require('./images/imran.jpg');
		case 'ibrahim55':
			return require('./images/ibrahim.jpg');
		case 'rokaiya56':
			return require('./images/borna.jpg');
		case 'sojib57':
			return require('./images/sojib.jpg');
		case 'ripon58':
			return require('./images/ripon.jpg');
		case 'shakil59':
			return require('./images/shakil.jpg');
		case 'shamim60':
			return require('./images/shamim.jpg');
		case 'sumon61':
			return require('./images/sumon.jpg');
		case 'mahadi62':
			return require('./images/mahadi.jpg');
		case 'fahmida63':
			return require('./images/fahmida.jpg');
		case 'maya64':
			return require('./images/maya.jpg');
		case 'istiak65':
			return require('./images/istiak.jpg');
		case 'asraf66':
			return require('./images/asraf.jpg');
		case 'jinath66':
			return require('./images/jinath.jpg');
		case 'mejba69':
			return require('./images/mejba.jpg');
		case 'simon70':
			return require('./images/simon.jpg');
		case 'ahsan72':
			return require('./images/ahsan.jpg');
		case 'shawonreza82':
			return require('./images/shawonreza.jpg');
		case 'rabin116':
			return require('./images/rabin.jpg');
		case 'plabon119':
			return require('./images/plabon.jpg');
		case 'khalid':
			return require('./images/khalid.jpg'); 
		default:
			return require('./images/profile.jpg');
	}
}

export default Avatar;